# Generated by Django 3.2.6 on 2021-08-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('song_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('NA', 'N/A'), ('downloading', 'downloading'), ('success', 'success'), ('fail', 'fail')], default='NA', max_length=20)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
